  name: repairnator-build
  on :
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  jobs:
      build:
        runs-on: ubuntu-latest
        env:
          GITHUB_OAUTH: ${{ secrets.GH_TOKEN }}
        steps:
          - uses: actions/checkout@v3
          - name: Set up JDK 1.8
            uses: actions/setup-java@v1
            with:
              java-version: 1.8
          - name: Repairnator Core
            env:
              TEST_PATH: src/repairnator-core/
            run: bash ./.ci/ci-run.sh

          - name: Repairnator Realtime
            env:
              TEST_PATH: src/repairnator-realtime/
              TEST_LIST: "**"
              run: bash ./.ci/ci-run-with-core.sh

          - name: Repairnator Maven Repair
            env:
              TEST_PATH: src/maven-repair/
              TEST_LIST: "**"
              run: bash ./.ci/ci-maven-repair.sh

          - name: Repairnator Pipeline
            env:
              TEST_PATH: src/repairnator-pipeline/
              TEST_LIST: "**"
            run: bash ./.ci/ci-run-with-core.sh
          - run: echo $${{ job.status }}
